patrik1109/timetable

pom.xml
src/main/java/timetable/Application.java
src/main/java/timetable/controllers/timeTableController.java
src/main/java/timetable/entities/Event.java
src/main/java/timetable/entities/Hall.java
src/main/java/timetable/service/EventService.java
src/main/java/timetable/service/EventServiceImpl.java
src/main/java/timetable/service/HallService.java
src/main/java/timetable/service/HallServiceImpl.java
src/main/java/timetable/thymeleaf_form/HallForm.java
src/main/resources/application.properties
src/main/resources/templates/editEvent.html
src/main/resources/templates/editHall.html
src/main/resources/templates/index.html
src/main/resources/templates/showHall.html

Egor01 edit hall

---

src/main/java/timetable/controllers/timeTableController.java
src/main/resources/application.properties
src/main/resources/templates/addHall.html
src/main/resources/templates/index.html

- add method addHall

---

src/main/resources/templates/index.html
src/main/resources/templates/showHall.html

egor01 table numbers and add button addHall

egor01 table numbers and add button addHall

---

src/main/java/timetable/controllers/timeTableController.java
src/main/java/timetable/entities/Event.java
src/main/java/timetable/responses/EventResponse.java
src/main/java/timetable/service/EventService.java
src/main/java/timetable/service/EventServiceImpl.java
src/main/java/timetable/thymeleaf_form/EventForm.java
src/main/resources/templates/AddEvent.html
src/main/resources/templates/editEvent.html
src/main/resources/templates/index.html
src/main/resources/templates/login.html
src/main/resources/templates/showHall.html

Qaban01 Colors

---

src/main/resources/templates/showHall.html

add color marker to table

---

src/main/resources/application.properties
src/main/resources/templates/AddEvent.html
src/main/resources/templates/editEvent.html
src/main/resources/templates/hallEvents.html
src/main/resources/templates/index.html
src/main/resources/templates/showHall.html

QABAN-01 CSS changes

---

src/main/resources/static/css/style.css

QABAN-01 style.css added

---

src/main/java/timetable/controllers/timeTableController.java
src/main/resources/application.properties
src/main/resources/templates/hallEvents.html

Qaban-01 no id in hall events fix

Qaban-01 no id in hall events fix

---

src/main/java/timetable/controllers/timeTableController.java
src/main/java/timetable/entities/Event.java
src/main/resources/application.properties

Qaban 01 wrong date fix

---

src/main/java/timetable/entities/Event.java
src/main/java/timetable/utils/TimeUtils.java

Qaban 01 timezone fix

---

src/main/resources/templates/showHall.html

QABAN-01 Hide and seek v1

---

src/main/java/timetable/controllers/timeTableController.java
src/main/resources/templates/showHall.html

Qaban-01 Generic Example

---

src/main/resources/templates/showHall.html

QABAN-01 clock is not showing up fix

QABAN-01 clock is not showing up fix

---

src/main/resources/templates/showHall.html

QABAN-01 base URL for clock

---

src/main/java/timetable/controllers/timeTableController.java
src/main/resources/templates/refreshTable.html
src/main/resources/templates/showHall.html

QABAN-01 Time is not visible fix

QABAN-01 Time is not visible fix

---

src/main/resources/templates/refreshTable.html

QABAN-01 refresh table fix

---

src/main/resources/application.properties
src/main/resources/templates/hallEvents.html

QABAN-01 hallEvents checkform fix

QABAN-01 hallEvents checkform fix

---

src/main/resources/templates/hallEvents.html

QABAN-01 hallEvents merge fix

---

src/main/java/timetable/controllers/timeTableController.java
src/main/resources/templates/hallEvents.html

QABAN-01 hallEvents onchange and no id fixes

QABAN-01 hallEvents onchange and no id fixes

---

src/main/resources/templates/hallEvents.html

Egor01 Kaban02
